var actorList = [
  {
    name: "Tom Hanks",
    image:
      "https://t1.gstatic.com/licensed-image?q=tbn:ANd9GcQaMZTWnBKqkR9bWNDh6TD_HZkSIIWtz265agrRvyzxfCwEL2_-n34fDPVgm1j6kWLsDv6gJoeumtNRgfg",
    movies: [
      "Forrest Gump",
      "Toy Story",
      "Cast Away",
      "The Da Vinci Code",
      "Saving Private Ryan",
      "Toy Story 2",
      "Toy Story 3",
      "A Man Called Otto",
      "1883",
      "Finch",
      "Toy Story 4",
      "Sully",
      "The Polar Express",
      "The Terminal",
      "The Green Mile",
    ],
    category: "Action",
  },
  {
    name: "Meryl Streep",
    image:
      "https://t1.gstatic.com/licensed-image?q=tbn:ANd9GcRHWCeAoWzaufVUKsbBPNFA0wCzvThk5c36S8rbFmIRuBQCbARoxnqwmN0t2bCxqXSIglZlWYK9QGX6KOk",
    movies: [
      "The Devil Wears Prada",
      "Mamma Mia!",
      "Kramer vs. Kramer",
      "Doubt",
      "The Iron Lady",
    ],
    category: "Drama",
  },
  {
    name: "Leonardo DiCaprio",
    image:
      "https://t0.gstatic.com/licensed-image?q=tbn:ANd9GcSdY1NpZdeMQrf8NiPwHDhMayah5RmDn_CJaQaF2MzEeFEAftcmNpeuIOsbu0muKrC7dJ5CK9p1KMwqBV4",
    movies: [
      "Titanic",
      "The Wolf of Wall Street",
      "The Revenant",
      "Inception",
      "The Departed",
      "Shutter Island",
      "Romeo & Juliet",
      "Once Upon a Time in Hollywood",
      "Catch me if you can",
      "Don't Look Up", 
      "Django Unchained", 
      "The Departed", 
      "The Man in the Iron Mask", 
      "The Great Gatsby",
      "Robin Hood", 
    ],
    category: "Action",
  },
  {
    name: "Angelina Jolie",
    image:
      "https://assets.vogue.com/photos/635683debc52d3d68b566853/4:3/w_2560%2Cc_limit/GettyImages-1349812316.jpg",
    movies: [
      "Lara Croft: Tomb Raider",
      "Mr. & Mrs. Smith",
      "Maleficent",
      "Wanted",
      "Changeling",
    ],
    category: "Action",
  },
  {
    name: "Will Smith",
    image:
      "https://s.yimg.com/ny/api/res/1.2/t29vjELsC6zx5dsHFLl_eg--/YXBwaWQ9aGlnaGxhbmRlcjt3PTY0MDtoPTgyMQ--/https://media.zenfs.com/en/cover_media_309/2484b07c35966e52ce71acb83c0b57e3",
    movies: [
      "Men in Black",
      "The Pursuit of Happyness",
      "Independence Day",
      "Ali",
      "I, Robot",
      "Bad Boys",
      "I am Legend",
      "Gemini Man",
    ],
    category: "Action",
  },
  {
    name: "Scarlett Johansson",
    image:
      "https://t1.gstatic.com/licensed-image?q=tbn:ANd9GcQ4piJSxeffOIAi2RYWlBKOKV5c_FtylD_BHb_3ZZCw-jfx684aAOEsBN-DZuy3BoqMgMCIhXWH97n36ZU",
    movies: [
      "Avengers Assemble",
      "Lost in Translation",
      "Lucy",
      "Jojo Rabbit",
      "Marriage Story",
      "Avengers Endgame",
      "Black Widow",
      "Under The Skin", 
      "Avengers Infinity War",
      "Don Jon",
      "Ghost In The Shell",
      "Avengers Age Of Ultron",
      "Captain America: The Winter Soldier",
      "Captain America: Civil War",
      "Sing",
      "Sing 2",
    ],
    category: "Action",
  },
  {
    name: "Brad Pitt",
    image:
      "https://t2.gstatic.com/licensed-image?q=tbn:ANd9GcSeBH5ZMgU-wE4p4eHv0eu1-dMDRsUVAbvjGJ8DhduWaPX4_RI-IMbNkkQkJALKnkg8r4uqYEiCTnKMShY",
    movies: [
      "Fight Club",
      "Inglourious Basterds",
      "Once Upon a Time in Hollywood",
      "Ocean's Eleven",
      "Troy",
      "World War Z",
      "Bullet Train", 
      "Babylon",
      "Mr & Mrs Smith", 
      "Seven",
      "Megamind",
      "Babel",
    ],
    category: "Action",
  },
  {
    name: "Keanu Reeves",
    image:
      "https://m.media-amazon.com/images/M/MV5BNGJmMWEzOGQtMWZkNS00MGNiLTk5NGEtYzg1YzAyZTgzZTZmXkEyXkFqcGdeQXVyMTE1MTYxNDAw._V1_.jpg",
    movies: [
      "The Matrix",
      "The Matrix Reloaded",
      "Speed",
      "Point Break",
      "The Matrix Resurrections",
      "Toy Story 4",
      "John Wick",
      "John Wick: Chapter 2",
      "John Wick: Chapter 3",
      "John Wick: Chapter 4",
      "Siberia",
      "A Very Bad Day",
      "Constantine",
      "The Matrix Revolutions",
      "Bill and Ted's Excellent Adventure",
      "Bill and Ted's Bogus Journey",
    ],
    category: "Action",
  },
  {
    name: "Mads Mikkelsen",
    image:
      "https://www.imdb.com/name/nm0586568/mediaviewer/rm2084346624/?ref_=nm_ov_ph",
    movies: [
      "Doctor Strange",
      "Rogue One",
      "Fantastic Beasts: The Secrets of Dumbledore",
      "Polar",
      "Another Round",
      "Casino Royale",
    ],
    category: "Action",
  },
  {
    name: "Ansel Elgort",
    image:
      "https://m.media-amazon.com/images/M/MV5BZTk1NWNmMTEtODdiMS00YzQ1LTg4MDQtMDczMzU5OGM3ZGFhXkEyXkFqcGdeQXVyODIzMDE1OTg@._V1_FMjpg_UX1000_.jpg",
    movies: [
      "Baby Driver",
      "Divergent",
      "The Fault in Our Stars",
      "Insurgent",
      "Allegiant",
      "Carrie",
    ],
    category: "Action",
  },
  {
    name: "Adam Driver",
    image:
      "https://t3.gstatic.com/licensed-image?q=tbn:ANd9GcTlW3jep_oUpqIkTbPrYfJ6fZVHanwqtaOf3eMIdU1xs4XaRda6j6uj1kXR7_4dbKD2bnAWWM9LJgnWuXs",
    movies: [
      "Star Wars: The Force Awakens",
      "Star Wars: The Last Jedi",
      "Star Wars: The Rise of Skywalker",
      "Blackkklansman",
      "65",
      "White Noise",
    ],
    category: "Action",
  },
  {
    name: "Ryan Reynolds",
    image:
      "https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcRDIJ-PkZ_U6WOLo7fm-UVwSZbyFb8fu5TVmvvErBzsxb_TmMMdJEyOMBT53C7zqxvuqDATtVONl_l5zPM",
    movies: [
      "Deadpool",
      "Deadpool 2",
      "The Adam Project",
      "Free Guy",
      "The Proposal",
      "Green Lantern",
      "6 Underground",
      "Detective Pikachu",
      "The Hitman's Bodyguard",
      "The Hitman's Wife's Bodyguard",
      "RIPD",
      "X-Men Origins: Wolverine",
      "Blade: Trinity",
    ],
    category: "Action",
  },
  {
    name: "Adam Sandler",
    image:
      "https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcRgoCDcGnPUsvsiS2GqOnN82gayxG_qeNqBmSc3hOKJJHzpEKzam4iPqHKoD1U8SvBNF24SrvpYPOzuXWs",
    movies: [
      "Happy Gilmore",
      "Billy Madison",
      "The Waterboy",
      "Big Daddy",
      "Grown Ups",
      "Just Go with It",
      "Click",
      "The Wedding Singer",
      "Blended",
      "Uncut Gems",
      "Hubie Halloween",
    ],
    category: "Comedy",
  },
  {
    name: "Jim Carrey",
    image:
      "https://m.media-amazon.com/images/M/MV5BMTQwMjAwNzI0M15BMl5BanBnXkFtZTcwOTY1MTMyOQ@@._V1_.jpg",
    movies: [
      "Ace Ventura: Pet Detective",
      "The Mask",
      "Dumb and Dumber",
      "Liar Liar",
      "The Truman Show",
      "Bruce Almighty",
      "Eternal Sunshine of the Spotless Mind",
      "Yes Man",
      "The Grinch",
      "Sonic the Hedgehog",
      "Me, Myself and Irene",
      "Dumber and Dumber 2",
      "Sonic the Hedgehog 2",
    ],
    category: "Comedy",
  },
  {
    name: "Steve Carell",
    image:
      "https://m.media-amazon.com/images/M/MV5BMjMyOTM2OTk1Ml5BMl5BanBnXkFtZTgwMTI3MzkyNjM@._V1_.jpg",
    movies: [
      "Anchorman: The Legend of Ron Burgundy",
      "The 40-Year-Old Virgin",
      "Little Miss Sunshine",
      "Dan in Real Life",
      "Crazy, Stupid, Love",
      "The Big Short",
      "Despicable Me",
      "Foxcatcher",
      "The Office",
      "The Morning Show",
    ],
    category: "Comedy",
  },
  {
    name: "Tina Fey",
    image:
      "https://m.media-amazon.com/images/M/MV5BNTJiOWYxMzQtNWZmYS00ZmNmLWE1ODktMGM3ZTkyYmE1YTBkXkEyXkFqcGdeQXVyMTAwOTg0NzU5._V1_.jpg",
    movies: [
      "Mean Girls",
      "Baby Mama",
      "Date Night",
      "Admission",
      "Sisters",
      "Whiskey Tango Foxtrot",
      "Soul",
      "30 Rock",
      "Unbreakable Kimmy Schmidt",
    ],
    category: "Comedy",
  },
  {
    name: "Seth Rogen",
    image:
      "https://flxt.tmsimg.com/assets/167023_v9_bb.jpg",
    movies: [
      "Superbad",
      "Knocked Up",
      "Pineapple Express",
      "This Is the End",
      "Neighbors",
      "The Interview",
      "Sausage Party",
      "Long Shot",
      "An American Pickle",
    ],
    category: "Comedy",
  },
  {
    name: "Emma Stone",
    image:
      "https://m.media-amazon.com/images/M/MV5BMjI4NjM1NDkyN15BMl5BanBnXkFtZTgwODgyNTY1MjE@._V1_.jpg",
    movies: [
      "Easy A",
      "Crazy, Stupid, Love",
      "The Help",
      "The Amazing Spider-Man",
      "La La Land",
      "The Favourite",
      "Zombieland",
      "Birdman",
      "Battle of the Sexes",
      "Cruella",
    ],
    category: "Rom-Com",
  },
  {
    name: "Ryan Gosling",
    image:
      "https://www.imdb.com/name/nm0331516/mediaviewer/rm525214208/?ref_=nm_ov_ph",
    movies: [
      "Crazy, Stupid, Love",
      "Drive",
      "The Place Beyond the Pines",
      "La La Land",
      "Blade Runner 2049",
      "The Notebook",
      "Blue Valentine",
      "The Big Short",
      "First Man",
    ],
    category: "Rom-Com",
  },
  {
    name: "Julia Roberts",
    image:
      "https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcQr8Py-a1YU77urOYldIKEOx-5WUCj3YOR4VjUzVZmbiFt2yMfraQCE3Za_e-yC3jlFxgEeV1obtjB1Qh0",
    movies: [
      "Pretty Woman",
      "My Best Friend's Wedding",
      "Notting Hill",
      "Runaway Bride",
      "Erin Brockovich",
      "Ocean's Eleven",
      "Eat Pray Love",
      "Wonder",
      "Homecoming",
    ],
    category: "Rom-Com",
  },
  {
    name: "Adam DeVine",
    image:
      "https://flxt.tmsimg.com/assets/534077_v9_bb.jpg",
    movies: [
      "Pitch Perfect",
      "Mike and Dave Need Wedding Dates",
      "The Intern",
      "Isn't It Romantic",
      "The Righteous Gemstones",
      "Workaholics",
      "Modern Family",
      "Magic Camp",
    ],
    category: "Rom-Com",
  },
  {
    name: "Jamie Lee Curtis",
    image:
      "https://i.guim.co.uk/img/media/d9e415042fdd9c71f8468ca25d22ce11c7494dd6/1_0_4997_3000/master/4997.jpg?width=1200&height=900&quality=85&auto=format&fit=crop&s=4c995963d6607378e31cb723d2bc5833",
    movies: [
      "Halloween",
      "Freaky Friday",
      "True Lies",
      "A Fish Called Wanda",
      "Trading Places",
      "Knives Out",
      "Halloween Kills",
      "Scream Queens",
    ],
    category: "Horror",
  },
  {
    name: "Johnny Depp",
    image:
      "https://ca-times.brightspotcdn.com/dims4/default/ba502d1/2147483647/strip/true/crop/7636x5091+0+0/resize/1200x800!/quality/80/?url=https%3A%2F%2Fcalifornia-times-brightspot.s3.amazonaws.com%2Fea%2F93%2F17290b4f4aefbc821640d2d35343%2Fgettyimages-1255359205.jpg",
    movies: [
      "Edward Scissorhands",
      "Sleepy Hollow",
      "Pirates of the Caribbean",
      "Charlie and the Chocolate Factory",
      "Alice in Wonderland",
      "Sweeney Todd: The Demon Barber of Fleet Street",
      "Black Mass",
      "Fantastic Beasts",
      "Corpse Bride",
    ],
    category: "Fantasy",
  },
  {
    name: "Emma Watson",
    image:
      "https://m.media-amazon.com/images/M/MV5BMTQ3ODE2NTMxMV5BMl5BanBnXkFtZTgwOTIzOTQzMjE@._V1_FMjpg_UX1000_.jpg",
    movies: [
      "Harry Potter",
      "Beauty and the Beast",
      "The Perks of Being a Wallflower",
      "Little Women",
      "The Circle",
      "Noah",
      "Regression",
      "Colonia",
    ],
    category: "Fantasy",
  },
  {
    name: "Robert Downey Jr",
    image: "https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcQijI6Sf7U-nKAfhHFmFBhVVVIxOfzI3QBeHqEjXJ7qcqbu98eqykx0UdmHrvt9Wx5hKilfZROD0mR85gk",
    movies: [
      "Iron Man",
      "Iron Man 2",
      "Iron Man 3",
      "Avengers Assemble",
      "Avengers: Age of Ultron",
      "Avengers Infinity War",
      "Avengers Endgame",
      "Captain America: Civil War",
      "Spiderman: Homecoming",
      "Dolittle",
      "Sherlock Holmes",
      "Sherlock Holmes: A Game of Shadows", 
      "Oppenheimer",
      "The Judge",
      "Tropic Thunder"
    ],
    category: "Action",
  },
  {
    name: "Chris Hemsworth",
    image: "https://i2-prod.mirror.co.uk/incoming/article29618950.ece/ALTERNATES/s1200c/0_Limitless-With-Chris-Hemsworth-New-York-Premiere.jpg",
    movies: [
      "Thor: Love and Thunder",
      "Extraction",
      "Men In Black: International",
      "Avengers Endgame",
      "Avengers Infinity War",
      "Thor: Ragnarok",
      "Avengers Assemble",
      "Avengers: Age of Ultron",
      "Ghostbusters", 
      "Doctor Strange",
      "Thor: The Dark World",
      "Thor", 
      "Rush",
      "Red Dawn", 
      "The Cabin in the Woods", 
    ],
    category: "Action",
  },
  {
    name: "Jennifer Aniston",
    image: "https://m.media-amazon.com/images/M/MV5BNjk1MjIxNjUxNF5BMl5BanBnXkFtZTcwODk2NzM4Mg@@._V1_FMjpg_UX1000_.jpg",
    movies: [
      "Murder Mystery 2",
      "Murder Mystery",
      "Just Go with It",
      "We're the Millers", 
      "Cake",
      "The Yellow Birds", 
      "Mothers Day", 
      "Horrible Bosses 2", 
      "She's Funny That Way",
      "Horrible Bosses",
    ], 
    category: "Comedy",
  },
  {
    name: "Morgan Freeman",
    image: "https://media.npr.org/assets/news/2010/06/01/freeman-db4a1244434ff8bbce7826bfd2aa38206e4750de-s1100-c50.jpg", 
    movies: [
      "The Shawshank Redemption", 
      "Now You See Me", 
      "Now You See Me 2",
      "Lucy", 
      "Seven Again", 
      "Oblivion", 
      "Hitmans Wifes Bodyguard",
      "Angel Has Fallen", 
      "Going in Style", 
      "High Crimes",
      "Last Knights", 
      "The Dark Knight",
      "The Dark Knight Rises", 
      "Batman Begins",
    ],
    category: "Drama",
  },
  {
    name: "Christan Bale", 
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Christian_Bale_2009.jpg/640px-Christian_Bale_2009.jpg", 
    movies: [
      "Batman Begins",
      "The Dark knight", 
      "The Dark Knight Rises", 
      "American Psycho", 
      "Thor Love and Thunder", 
      "The Machinist", 
      "The Prestige", 
      "Terminator: Salvation", 
      "Ford v Ferrari",
      "American Hustle", 
      "Empire of the Sun",
    ], 
    category: "Action"
  }, 
  {
    name: "Tom Hardy",
    image: "https://static.independent.co.uk/s3fs-public/thumbnails/image/2016/02/28/14/hardy-getty2.jpg", 
    movies: [
      "Inception",
      "Venom",
      "Venom: Let There Be Carnage",
      "Child 44",
      "Legend",
      "Locke", 
      "Capone",
      "The Drop",
      "The Dark Knight Rises",
      "Lawless",
      "Mad Max: Fury Road",
      "Dunkirk",

    ], 
    category: "Action"
  }
];